name: Run on issues, update photo

on:
  issues:
    types: [opened, reopened]

permissions:
  contents: write
  issues: write

jobs:
  my_new_image_job:
    name: Change the photo if issue is created with NEW in its title
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'NEW')

    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for your request @${{ github.event.issue.user.login }} ‚ú®

            ...running action now! üèóÔ∏è

      - name: Checkout
        uses: actions/checkout@v4

      - name: Change to 3 random images
        run: ./.github/actions/scripts/changeimage.ps1
        shell: pwsh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated based on raised issue #${{ github.event.issue.number }} by @${{ github.event.issue.user.login }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          comment: |
            Updated the README.md with new random photos:

            ![${{ env.filename1 }}](https://github.com/jaapbrasser/jaapbrasser/blob/master/Assets/${{ env.filename1 }}?raw=true)
            ![${{ env.filename2 }}](https://github.com/jaapbrasser/jaapbrasser/blob/master/Assets/${{ env.filename2 }}?raw=true)
            ![${{ env.filename3 }}](https://github.com/jaapbrasser/jaapbrasser/blob/master/Assets/${{ env.filename3 }}?raw=true)

            Thanks for your contribution @${{ github.event.issue.user.login }}!
